# Generated by Django 4.2 on 2023-04-30 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_highlightedtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightedtext',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
